---
title: "Read in raw data"
author: "Alan Jackson"
date: "April 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library("stringr") # string tools
library("readxl") # read excel files
library("lettercase") # fiddle with letter case
library("lubridate") # handle dates
library(RCurl)
library(reshape2)

knitr::opts_chunk$set(echo = TRUE)
```




```{r read pollen data}

path <- "https://www.houstontx.gov/health/Pollen-Mold/Pollen_Archives/"

#   Read in files using month names

#   Build a list of valid url's

url_list <- tribble(~url)

for (yr in as.character(2013:2019)) {
  for (mon in tolower(month.name)) {
    if (yr=="2013" & mon=="february") {mon <- "febraury"}
    url <- paste0(mon, "_", yr, "_pollen.xls")
    if (yr=="2018" | yr=="2019" |
        (yr=="2017"&(mon=="november"|mon=="december"))) {
          url <- paste0(mon, "_", yr, "_pollen.xlsx")
    }
    if(yr=="2018" & mon=="june") {url <- paste0(mon, "_", yr, "_pollen.xls")} 
    if(yr=="2018" & mon=="march") {next} # bad file lurking out there
    if (!url.exists(paste0(path,url))) {print(paste(url, "does not exist"))
                            next}
    #   add to url_list
    url_list <- add_row(url_list, url=url)
  }
}

#   Read in files using numeric months

for (yr in as.character(2013:2019)) {
  for (mon in sprintf("%02d", 1:12)) {
    url <- paste0(yr, mon, "-pollen-count.xls")
    if (grepl("201902", url)) {url <- paste0(url, "x")}
    if (!url.exists(paste0(path,url))) {print(paste(url, "does not exist"))
                            next}
    #   add to url_list
    url_list <- add_row(url_list, url=url)
  }
}

####################################
# now let's read the files and save
####################################

#   First read the urls into local files

for (url in url_list[,1]){
  download.file(paste0(path, url), destfile=url, mode="wb")
}

df <- tribble()
for (url in url_list$url){
  print(url)
  fileout <- paste0(url,".rds")
  df2 <- read_excel(url, col_names=FALSE)  
  saveRDS(df2, fileout)
}

```

##    Serious cleanup time

```{r cleanup and consolidate}

keep <- url_list

df1 <- readRDS(paste0(url_list[1,1], ".rds"))
df2 <- readRDS(paste0(url_list[2,1], ".rds"))
dftest <- readRDS(paste0(url_list[27,1],".rds"))

# Read in df's from disk



clean = function(data) {

  # Recode column names
  names.row = grep("DATE", data[, 1, drop=TRUE], ignore.case=TRUE)
  data[names.row, which(is.na(data[names.row,]))] <- 
    rep("NULL", sum(is.na(data[names.row,]))) # sometimes the variable is NA
  recode_vals = translate$to %>% set_names(translate$from)
  old_names = unlist(data[names.row, ][-1]) 
  names(data) = c("Date", recode(old_names, !!!recode_vals))
  
  # Get Month and Year for dates
  names.col = grep("Month:", data, ignore.case=TRUE)
  names.row = grep("Month:", data[, names.col, drop=TRUE], ignore.case=TRUE)
  #mon <- str_remove(data[1,]$Date, "Month:\\s*")
  mon  <- str_remove(data[names.row, names.col], "Month:\\s*|MONTH:\\s*")
  #mon  <- str_remove(data[names.row,]$Date, "Month:\\s*|MONTH:\\s*")
  #mon <- match(mon, toupper(month.name))
  names.col = grep("Year:", data, ignore.case=TRUE)
  names.row = grep("Year", data[, names.col, drop=TRUE], ignore.case=TRUE)
  yr  <- str_remove(data[names.row, names.col], "YEAR:\\s*|Year:\\s*")
  #yr  <- str_remove(data[2,]$Date, "YEAR:\\s*")

  # Remove Month, Year, Date, POLLEN, and Total rows
  data = data[!grepl("Month|YEAR|DATE|Total|POLLEN", data$Date, ignore.case=TRUE), ]
  data = data[!is.na(data$Date),]
  
  # Change Date column to correct dates
  data$Date = paste(yr, mon, data$Date, sep="-")
  data$Date = lubridate::ymd(data$Date)
  data = data[!is.na(data$Date),] # for things like Feb 31
  
  print(data$Date[1])
  
  data
}


translate <- tribble(
  ~from,                        ~to,
"Ashe Juniper / Bald Cypress",  "Ashe_JuniperOrBald_Cypress", 
"Alnus(Alder)",                 "Alnus",
"Black Gum",                    "Black_Gum", 
"Black Walnut",                 "Black_Walnut", 
"Cotton Wood",                  "Cotton_Wood",
"Glandular Mesquite",           "Glandular_Mesquite", 
"Osage Orange",                 "Osage_Orange", 
"Sweet Gum",                    "Sweet_Gum", 
"Gingko Biloba",                "Gingko_Biloba",  
"Burweed / Marshelder",         "BurweedOrMarshelder", 
"Dog Fennel",                   "Dog_Fennel", 
"Lamb's Quarters",              "Lambs_Quarters", 
"Partridge Pea",                "Partridge_Pea", 
"Plum Grannet",                 "Plum_Grannet", 
"WILLOW",                       "Willow", 
"plantago(plantain)",           "Plantago", 
"Plantago(Plantain)",           "Plantago", 
"Plantago(plantain)",           "Plantago", 
"PLANTAGO",                     "Plantago", 
"Walnut(juglans)",              "Walnut", 
"Other weed pollen",            "Other_Weed", 
"Other weed/unidentified",      "Other_Weed", 
"other weed pollen",            "Other_Weed", 
"other weed",                   "Other_Weed", 
"Other Weed",                   "Other_Weed", 
"OTHER WEED",                   "Other_Weed", 
"OTHER TREE",                   "Other_Tree", 
"Other Tree/Unidentified",      "Other_Tree", 
"other tree pollen",            "Other_Tree", 
"OTHER TREE POLLEN",            "Other_Tree", 
"Other tree pollen",            "Other_Tree", 
"Other Tree",                   "Other_Tree", 
"Wild Carrot",                  "Wild_Carrot" 
)


df <- map_df(mget(ls(pattern = "df[0-9]")), clean) %>%  
  select(-contains("Total"), -contains("TOTAL"), -contains("Tech"))

df <- df %>% mutate_if(is.character,as.numeric)

saveRDS(df, "MasterPollenData.rds")


#df63
#df69
#df69new <- editData(df69)

```

##  start looking at data

```{r look at data}


df %>% melt(id="Date") %>% 
  ggplot(aes(x=Date, y=value, color=variable)) + 
  geom_line()

df %>% skim()

df %>% select(Date, Ash, Ashe_JuniperOrBald_Cypress, Elm, Oak, Ragweed, Cedar, Pine) %>% 
  melt(id="Date") %>% 
  ggplot(aes(x=Date, y=value, color=variable)) + 
  geom_line()

```

##    Let's look at Oak alone

```{r oak study}

oak <- df %>% select(Date, Oak)

# Impute missing values


# Wrap plots by year




```



